/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui;

/**
 *
 * @author Jasmine
 */
public class Payment extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Payment.class.getName());

    /**
     * Creates new form Payment
     */
    public Payment(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login3 = new javax.swing.JPanel();
        Username1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel70 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TablePM = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Login3.setBackground(new java.awt.Color(252, 228, 236));
        Login3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Login3KeyPressed(evt);
            }
        });

        Username1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Username1.setForeground(new java.awt.Color(209, 15, 122));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(209, 15, 122));
        jLabel6.setText("PAYMENTS");

        jPanel4.setBackground(new java.awt.Color(236, 64, 122));

        jLabel70.setFont(new java.awt.Font("Vivaldi", 1, 22)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setText("Glam Up Salon");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel70, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel70)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        TablePM.setBackground(new java.awt.Color(248, 221, 232));
        TablePM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PaymentID", "AppointmentID", "PaymentMethod", "AmountPaid", "TotalAmount", "Status", "PaymentDate"
            }
        ));
        jScrollPane6.setViewportView(TablePM);

        javax.swing.GroupLayout Login3Layout = new javax.swing.GroupLayout(Login3);
        Login3.setLayout(Login3Layout);
        Login3Layout.setHorizontalGroup(
            Login3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Login3Layout.createSequentialGroup()
                .addGroup(Login3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Login3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE))
                    .addGroup(Login3Layout.createSequentialGroup()
                        .addGroup(Login3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Login3Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(Username1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Login3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Login3Layout.setVerticalGroup(
            Login3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Login3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(34, 34, 34)
                .addComponent(Username1)
                .addGap(49, 49, 49)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Login3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Login3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AACustomerCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AACustomerCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AACustomerCBActionPerformed

    private void AASaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AASaveBtnActionPerformed

        String username = LoginUsernameTxt.getText().trim();
        String password = new String(LoginPasswordTxt.getPassword()).trim();

        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Please enter your username.", "Missing Field",
                JOptionPane.WARNING_MESSAGE);
            LoginUsernameTxt.requestFocus();
            return;
        }
        if (password.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Please enter your password.", "Missing Field",
                JOptionPane.WARNING_MESSAGE);
            LoginPasswordTxt.requestFocus();
            return;
        }

        try {
            java.sql.Connection con = DBConnection.getConnection();
            java.sql.PreparedStatement ps = con.prepareStatement(
                "SELECT UserID, Role FROM Users " +
                "WHERE Username=? AND PasswordHash=? AND IsActive=1");
            ps.setString(1, username);
            ps.setString(2, password);
            java.sql.ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                String role = rs.getString("Role");
                int userID = rs.getInt("UserID");

                rs.close();
                ps.close();
                con.close();
                java.awt.CardLayout cl = (java.awt.CardLayout) MainPanel.getLayout();

                switch (role) {
                    case "Admin":
                    cl.show(MainPanel, "AdminDashboard");
                    loadTodaySchedule();
                    break;
                    case "Staff":
                    cl.show(MainPanel, "StaffDashboard");
                    break;
                    default:
                    JOptionPane.showMessageDialog(this,
                        "Unknown role: " + role,
                        "Login Error", JOptionPane.ERROR_MESSAGE);
                }

            } else {
                JOptionPane.showMessageDialog(this,
                    "Invalid username or password.",
                    "Login Failed",
                    JOptionPane.ERROR_MESSAGE);
                LoginPasswordTxt.setText("");
                LoginPasswordTxt.requestFocus();
            }

        } catch (java.sql.SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Database error:\n" + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_AASaveBtnActionPerformed

    private void Login3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Login3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Login3KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Payment dialog = new Payment(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AACustomerCB;
    private javax.swing.JComboBox<String> AACustomerCB1;
    private javax.swing.JComboBox<String> AACustomerCB3;
    private javax.swing.JComboBox<String> AADateCB;
    private javax.swing.JComboBox<String> AADateCB1;
    private javax.swing.JComboBox<String> AADateCB3;
    private javax.swing.JButton AASaveBtn;
    private javax.swing.JButton AASaveBtn1;
    private javax.swing.JButton AASaveBtn3;
    private javax.swing.JComboBox<String> AAServicesCB;
    private javax.swing.JComboBox<String> AAServicesCB1;
    private javax.swing.JComboBox<String> AAServicesCB3;
    private javax.swing.JComboBox<String> AAStatusCB;
    private javax.swing.JComboBox<String> AAStatusCB1;
    private javax.swing.JComboBox<String> AAStatusCB3;
    private javax.swing.JComboBox<String> AAStylistCB;
    private javax.swing.JComboBox<String> AAStylistCB1;
    private javax.swing.JComboBox<String> AAStylistCB3;
    private javax.swing.JPanel Login;
    private javax.swing.JPanel Login1;
    private javax.swing.JPanel Login2;
    private javax.swing.JPanel Login3;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Password1;
    private javax.swing.JLabel Password3;
    private javax.swing.JLabel Password4;
    private javax.swing.JLabel Password7;
    private javax.swing.JLabel Password8;
    private javax.swing.JTable TablePM;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel Username1;
    private javax.swing.JLabel Username10;
    private javax.swing.JLabel Username11;
    private javax.swing.JLabel Username12;
    private javax.swing.JLabel Username13;
    private javax.swing.JLabel Username19;
    private javax.swing.JLabel Username2;
    private javax.swing.JLabel Username20;
    private javax.swing.JLabel Username21;
    private javax.swing.JLabel Username22;
    private javax.swing.JLabel Username23;
    private javax.swing.JLabel Username3;
    private javax.swing.JLabel Username4;
    private javax.swing.JLabel Username6;
    private javax.swing.JLabel Username9;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane6;
    // End of variables declaration//GEN-END:variables
}
