/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author Jasmine
 */




public class UpdateAppointment extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UpdateAppointment.class.getName());
    private javax.swing.JTable AATable;
private int selectedRow;

    /**
     * Creates new form UpdateAppointment
     */
    public UpdateAppointment(java.awt.Frame parent, boolean modal, javax.swing.JTable table, int row) {
  super(parent, modal);
    this.AATable = table;
    this.selectedRow = row;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Username6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel68 = new javax.swing.JLabel();
        Username7 = new javax.swing.JLabel();
        CancelUA = new javax.swing.JButton();
        SaveUA = new javax.swing.JButton();
        StatusUA = new javax.swing.JComboBox<>();
        StylistUA = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Login.setBackground(new java.awt.Color(252, 228, 236));
        Login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LoginKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(209, 15, 122));
        jLabel4.setText("    UPDATE APPOINTMENT");

        Username6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Username6.setForeground(new java.awt.Color(209, 15, 122));
        Username6.setText("Status");

        jPanel2.setBackground(new java.awt.Color(236, 64, 122));

        jLabel68.setFont(new java.awt.Font("Vivaldi", 1, 22)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setText("Glam Up Salon");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel68)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        Username7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Username7.setForeground(new java.awt.Color(209, 15, 122));
        Username7.setText("Stylist");

        CancelUA.setBackground(new java.awt.Color(248, 187, 217));
        CancelUA.setForeground(new java.awt.Color(236, 64, 122));
        CancelUA.setText("Cancel");

        SaveUA.setBackground(new java.awt.Color(236, 64, 122));
        SaveUA.setText("Save");
        SaveUA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveUAActionPerformed(evt);
            }
        });

        StatusUA.setBackground(new java.awt.Color(255, 255, 255));
        StatusUA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));
        StatusUA.setSelectedIndex(-1);
        StatusUA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusUAActionPerformed(evt);
            }
        });

        StylistUA.setBackground(new java.awt.Color(255, 255, 255));
        StylistUA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Raven Bituin", "Jasmine Tubilla", "Eujyll Abella", "Clysce Perez" }));

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addComponent(CancelUA)
                        .addGap(27, 27, 27)
                        .addComponent(SaveUA))
                    .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Username6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Username7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(StatusUA, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(StylistUA, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel4)
                .addGap(43, 43, 43)
                .addComponent(Username6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StatusUA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Username7)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StylistUA, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 150, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CancelUA)
                            .addComponent(SaveUA))
                        .addGap(79, 79, 79))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void SaveUAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveUAActionPerformed
        // TODO add your handling code here
    
     String status = (String) StatusUA.getSelectedItem();
    String stylist = (String) StylistUA.getSelectedItem();

    if (status == null || status.trim().isEmpty() || stylist == null || stylist.trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(null,
            "Please fill in all fields.", "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String url = "jdbc;sqlserver;//localhost;1433;" +
            "databaseName=SalonDB;" +
            "user=sa;" +
            "password=tubilla;" +
            "encrypt=true;" +
            "trustServerCertificate=true;";

        Connection con = DriverManager.getConnection(url);

        // ✅ Now works — AATable and selectedRow passed from main panel
        String id = AATable.getValueAt(selectedRow, 0).toString();

        // Replace "Appointments" with your actual table name
        String updateQuery = "UPDATE AppointmentTable SET Stylists = ?, Status = ? WHERE AppointmentID = ?";
        PreparedStatement pst = con.prepareStatement(updateQuery);
        pst.setString(1, stylist);
        pst.setString(2, status);
        pst.setString(3, id);

        pst.executeQuery());
        JOptionPane.showMessageDialog(this, "Appointment updated successfully!");

        pst.close();
        con.close();

    } catch (ClassNotFoundException e) {
        JOptionPane.showMessageDialog(this, "Driver not found: " + e.getMessage());
    } catch (java.sql.SQLException e) {
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Unexpected error: " + e.getMessage());
    }
    }//GEN-LAST:event_SaveUAActionPerformed

    private void LoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoginKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginKeyPressed

    private void StatusUAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusUAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusUAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                UpdateAppointment dialog = new UpdateAppointment(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelUA;
    private javax.swing.JPanel Login;
    private javax.swing.JButton SaveUA;
    private javax.swing.JComboBox<String> StatusUA;
    private javax.swing.JComboBox<String> StylistUA;
    private javax.swing.JLabel Username6;
    private javax.swing.JLabel Username7;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
